var a = 10;
var b = 15;
var soma = a + b;
document.getElementById("ex_1").innerHTML = "1) " + a + " + " + b + " = " + soma + " " + typeof soma;
var a = "10";
var b = 2;
var soma = a + b;
document.getElementById("ex_2").innerHTML = "2) " + a + " + " + b + " = " + soma + " " + typeof soma;
var a = "10";
var b = 2;
var soma = a * b;
document.getElementById("ex_3").innerHTML = "3) " + a + " x " + b + " = " + soma + " " + typeof soma;
var a = "10";
var b = 3;
var soma = a / b;
document.getElementById("ex_4").innerHTML = "4) " + a + " / " + b + " = " + soma + " " + typeof soma;
var a = "10";
var b = 3;
var soma = a % b;
document.getElementById("ex_5").innerHTML = "5) " + a + " % " + b + " = " + soma + " " + typeof soma;
var a = 10;
var b = true;
var soma = a + b;
document.getElementById("ex_6").innerHTML = "6) " + a + " + " + b + " = " + soma + " " + typeof soma;
var a = 10;
var b = "10";
var soma = a == b;
document.getElementById("ex_7").innerHTML = "7) " + a + " == " + b + " = " + soma + " " + typeof soma;
var a = 10;
var b = "10";
var soma = a === b;
document.getElementById("ex_8").innerHTML = "8) " + a + " === " + b + " = " + soma + " " + typeof soma;
var a = 10;
var b = 11;
var soma = a < b;
document.getElementById("ex_9").innerHTML = "9) " + a + " < " + b + " = " + soma + " " + typeof soma;
var a = 10;
var b = 12;
var soma = a > b;
document.getElementById("ex_10").innerHTML = "10) " + a + " > " + b + " = " + soma + " " + typeof soma;
var a = 10;
var b = 10.1;
var soma = a <= b;
document.getElementById("ex_11").innerHTML = "11) " + a + " <= " + b + " = " + soma + " " + typeof soma;
var a = 10;
var b = 9.99;
var soma = a > b;
document.getElementById("ex_12").innerHTML = "12) " + a + " > " + b + " = " + soma + " " + typeof soma;
var a = 10;
var b = "dez";
var soma = a != b;
document.getElementById("ex_13").innerHTML = "13) " + a + " != " + b + " = " + soma + " " + typeof soma;
var a = 10;
var b = true;
var soma = a + b;
document.getElementById("ex_14").innerHTML = "14) " + a + " + " + b + " = " + soma + " " + typeof soma;
var a = "dez";
var b = true;
var soma = a + b;
document.getElementById("ex_15").innerHTML = "15) " + a + " + " + b + " = " + soma + " " + typeof soma;
var a = 10;
var b = false;
var soma = a + b;
document.getElementById("ex_16").innerHTML = "16) " + a + " + " + b + " = " + soma + " " + typeof soma;
var a = 10;
var b = false;
var soma = a * b;
document.getElementById("ex_17").innerHTML = "17) " + a + " x " + b + " = " + soma + " " + typeof soma;
var a = true;
var b = true;
var soma = a + b;
document.getElementById("ex_18").innerHTML = "18) " + a + " + " + b + " = " + soma + " " + typeof soma;
var a = 10;
var b = 10;
var soma = a + b;
document.getElementById("ex_19").innerHTML = "19) " + a + " + " + b + " = " + soma + " " + typeof soma;
var a = 10;
var b = 10;
var soma = a - b;
document.getElementById("ex_20").innerHTML = "20) " + a + " - " + b + " = " + soma + " " + typeof soma;
var a = 1;
var b = 1;
var soma = a & b;
document.getElementById("ex_21").innerHTML = "21) " + a + " & " + b + " = " + soma + " " + typeof soma;
var a = 1;
var b = 0;
var soma = a & b;
document.getElementById("ex_22").innerHTML = "22) " + a + " & " + b + " = " + soma + " " + typeof soma;
var a = 0;
var b = 0;
var soma = a & b;
document.getElementById("ex_23").innerHTML = "23) " + a + " & " + b + " = " + soma + " " + typeof soma;
var a = 0;
var b = 1;
var soma = a & b;
document.getElementById("ex_24").innerHTML = "24) " + a + " & " + b + " = " + soma + " " + typeof soma;
var a = 0;
var b = 1;
var soma = a / b;
document.getElementById("ex_25").innerHTML = "25) " + a + " / " + b + " = " + soma + " " + typeof soma;
var a = 5;
var b = 5;
var soma = a + b == 10;
document.getElementById("ex_26").innerHTML = "26) " + a + " + " + b + " == " + "10 " + soma + " " + typeof soma;
var a = "5";
var b = "5";
var soma = a + b == 10;
document.getElementById("ex_27").innerHTML = "27) " + a + " + " + b + " == " + "10 " + soma + " " + typeof soma;
var a = "5";
var b = 2;
var soma = a * b > 9;
document.getElementById("ex_28").innerHTML = "28) " + a + " x " + b + " > 9 " + soma + " " + typeof soma;
var a = 10;
var b = 10;
var soma = (a + b) * 2;
document.getElementById("ex_29").innerHTML = "29) " + "(10 + 10) * 2" + " = " + soma + " " + typeof soma;
var a = 10;
var b = 10;
var soma = a + b * 2;
document.getElementById("ex_30").innerHTML = "30) " + "10 + 10 * 2" + " = " + soma + " " + typeof soma;


